version: '3.8'

services:
  kansofy-trade:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_PATH=/app/data/kansofy_trade.db
      - UPLOAD_DIR=/app/uploads
      - HOST=0.0.0.0
      - PORT=8000
      - MCP_SERVER_PORT=8001
      - DEBUG=false
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s